{
	"affected_release": [
		{
			"advisory": "RHSA-2011:0260",
			"cpe": "cpe:/o:redhat:enterprise_linux:4",
			"package": "python-0:2.3.4-14.9.el4",
			"product_name": "Red Hat Enterprise Linux 4",
			"release_date": "2011-02-16T00:00:00Z"
		},
		{
			"advisory": "RHSA-2011:0027",
			"cpe": "cpe:/o:redhat:enterprise_linux:5",
			"package": "python-0:2.4.3-43.el5",
			"product_name": "Red Hat Enterprise Linux 5",
			"release_date": "2011-01-13T00:00:00Z"
		}
	],
	"bugzilla": {
		"description": "CVE-2009-4134 CVE-2010-1449 CVE-2010-1450 python: rgbimg: multiple security issues",
		"id": "541698",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=541698"
	},
	"csaw": false,
	"cvss": {
		"cvss_base_score": "5.1",
		"cvss_scoring_vector": "AV:N/AC:H/Au:N/C:P/I:P/A:P",
		"status": "verified"
	},
	"details": [
		"Buffer underflow in the rgbimg module in Python 2.5 allows remote attackers to cause a denial of service (application crash) via a large ZSIZE value in a black-and-white (aka B/W) RGB image that triggers an invalid pointer dereference."
	],
	"name": "CVE-2009-4134",
	"public_date": "2010-05-10T00:00:00Z",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2009-4134\nhttps://nvd.nist.gov/vuln/detail/CVE-2009-4134"
	],
	"statement": "The Red Hat Security Response Team has rated this issue as having low security\nimpact, a future update may address this flaw.",
	"threat_severity": "Low"
}
