{
	"name": "CVE-2017-12598",
	"threat_severity": "Low",
	"public_date": "2017-08-05T00:00:00Z",
	"bugzilla": {
		"description": "CVE-2017-12598 opencv: out-of-bounds read error in the cv::RBaseStream::readBlock function",
		"id": "1483893",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1483893"
	},
	"cvss3": {
		"cvss3_base_score": "3.3",
		"cvss3_scoring_vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
		"status": "draft"
	},
	"cwe": "CWE-125",
	"details": [
		"OpenCV (Open Source Computer Vision Library) through 3.3 has an out-of-bounds read error in the cv::RBaseStream::readBlock function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 8-opencv-invalid-read-fread test case."
	],
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2017-12598\nhttps://nvd.nist.gov/vuln/detail/CVE-2017-12598"
	],
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:6",
			"fix_state": "Will not fix",
			"package_name": "opencv",
			"product_name": "Red Hat Enterprise Linux 6"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Will not fix",
			"package_name": "opencv",
			"product_name": "Red Hat Enterprise Linux 7"
		}
	],
	"csaw": false
}
