{
	"bugzilla": {
		"description": "improper initialization in dump_entry_data_list() in maxminddb.c",
		"id": "1895379",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1895379"
	},
	"csaw": false,
	"cvss3": {
		"cvss3_base_score": "6.5",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
		"status": "draft"
	},
	"cwe": "CWE-665->CWE-170->CWE-122",
	"details": [
		"libmaxminddb before 1.4.3 has a heap-based buffer over-read in dump_entry_data_list in maxminddb.c.",
		"An improper initialization issue was found in libmaxminddb. A remote user could exploit this flaw by sending a specially crafted MaxMind DB file that, when parsed by an application linked to libmaxminddb, would possibly crash the application, resulting in a denial of service condition."
	],
	"name": "CVE-2020-28241",
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Will not fix",
			"package_name": "libmaxminddb",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Affected",
			"package_name": "libmaxminddb",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:9",
			"fix_state": "Not affected",
			"package_name": "libmaxminddb",
			"product_name": "Red Hat Enterprise Linux 9"
		}
	],
	"public_date": "2020-08-04T00:00:00Z",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2020-28241\nhttps://nvd.nist.gov/vuln/detail/CVE-2020-28241"
	],
	"threat_severity": "Moderate",
	"upstream_fix": "libmaxminddb 1.4.3"
}
