{
	"name": "CVE-2020-8663",
	"threat_severity": "Important",
	"public_date": "2020-06-30T19:00:00Z",
	"bugzilla": {
		"description": "CVE-2020-8663 envoy: Resource exhaustion when accepting too many connections",
		"id": "1844254",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1844254"
	},
	"cvss3": {
		"cvss3_base_score": "7.5",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
		"status": "verified"
	},
	"cwe": "CWE-400",
	"details": [
		"Envoy version 1.14.2, 1.13.2, 1.12.4 or earlier may exhaust file descriptors and/or memory when accepting too many connections.",
		"A flaw was found in envoy in versions through 1.14.1. Accepting too many connections may lead to an exhaustion of file descriptors and/or memory. The highest threat from this vulnerability is to system availability."
	],
	"statement": "A uncontrolled resource consumption vulnerability was found in Envoy. An attacker can initiate too many connections to the proxy potentially exhausting file descriptors and/or memory resulting in a denial of service.",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2020-8663\nhttps://nvd.nist.gov/vuln/detail/CVE-2020-8663\nhttps://istio.io/latest/news/security/istio-security-2020-007/"
	],
	"acknowledgement": "Red Hat would like to thank the Envoy security team for reporting this issue.",
	"affected_release": [
		{
			"advisory": "RHSA-2020:2864",
			"cpe": "cpe:/a:redhat:service_mesh:1.0::el8",
			"package": "servicemesh-proxy-0:1.0.11-1.el8",
			"product_name": "OpenShift Service Mesh 1.0",
			"release_date": "2020-07-07T00:00:00Z"
		},
		{
			"advisory": "RHSA-2020:2798",
			"cpe": "cpe:/a:redhat:service_mesh:1.1::el8",
			"package": "servicemesh-proxy-0:1.1.4-2.el8",
			"product_name": "OpenShift Service Mesh 1.1",
			"release_date": "2020-07-01T00:00:00Z"
		}
	],
	"upstream_fix": "envoy 1.14.2",
	"csaw": false
}
