{
	"name": "CVE-2011-4944",
	"threat_severity": "Low",
	"public_date": "2011-11-30T00:00:00Z",
	"bugzilla": {
		"description": "python: distutils creates ~/.pypirc insecurely",
		"id": "758905",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=758905"
	},
	"cvss": {
		"cvss_base_score": "1.2",
		"cvss_scoring_vector": "AV:L/AC:H/Au:N/C:P/I:N/A:N",
		"status": "verified"
	},
	"details": [
		"Python 2.6 through 3.2 creates ~/.pypirc with world-readable permissions before changing them after data has been written, which introduces a race condition that allows local users to obtain a username and password by reading this file."
	],
	"statement": "The Red Hat Security Response Team has rated this issue as having low security impact. This issue is not currently planned to be addressed in future updates. For additional information, refer to the Issue Severity Classification: https://access.redhat.com/security/updates/classification/.",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2011-4944\nhttps://nvd.nist.gov/vuln/detail/CVE-2011-4944"
	],
	"affected_release": [
		{
			"advisory": "RHSA-2012:0745",
			"cpe": "cpe:/o:redhat:enterprise_linux:5",
			"package": "python-0:2.4.3-46.el5_8.2",
			"product_name": "Red Hat Enterprise Linux 5",
			"release_date": "2012-06-18T00:00:00Z"
		},
		{
			"advisory": "RHSA-2012:0744",
			"cpe": "cpe:/o:redhat:enterprise_linux:6",
			"package": "python-0:2.6.6-29.el6_2.2",
			"product_name": "Red Hat Enterprise Linux 6",
			"release_date": "2012-06-18T00:00:00Z"
		}
	],
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:4",
			"fix_state": "Will not fix",
			"package_name": "python",
			"product_name": "Red Hat Enterprise Linux 4"
		}
	],
	"csaw": false
}
