{
	"bugzilla": {
		"description": "constant-time-defeating optimisations issue in the compare_digest function in Lib/hmac.p",
		"id": "2238753",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2238753"
	},
	"csaw": false,
	"cvss3": {
		"cvss3_base_score": "5.9",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
		"status": "draft"
	},
	"cwe": "CWE-362",
	"details": [
		"An issue was discovered in compare_digest in Lib/hmac.py in Python through 3.9.1. Constant-time-defeating optimisations were possible in the accumulator variable in hmac.compare_digest.",
		"A constant-time-defeating optimization issue was found in python. This issue occurs when sending a specially crafted request, which could allow an attacker to obtain sensitive information."
	],
	"mitigation": {
		"lang": "en:us",
		"value": "As per upstream, either make the accumulator variable result a volatile unsigned char instead of unsigned char or use instead use CRYPTO_memcmp from OpenSSL/BoringSSL when SSL is available as SSL libraries are more secure when it comes to timing based vulnerabilities.\nhttps://github.com/python/cpython/issues/84968"
	},
	"name": "CVE-2022-48566",
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:6",
			"fix_state": "Out of support scope",
			"package_name": "python",
			"product_name": "Red Hat Enterprise Linux 6"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Out of support scope",
			"package_name": "python",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Out of support scope",
			"package_name": "python3",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "gimp:flatpak/python2",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "inkscape:flatpak/python2",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "python27:2.7/python2",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "python3",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "python3.11",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "python36:3.6/python36",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "python39:3.9/python39",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:9",
			"fix_state": "Not affected",
			"package_name": "python3.11",
			"product_name": "Red Hat Enterprise Linux 9"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:9",
			"fix_state": "Not affected",
			"package_name": "python3.9",
			"product_name": "Red Hat Enterprise Linux 9"
		},
		{
			"cpe": "cpe:/a:redhat:rhel_software_collections:3",
			"fix_state": "Not affected",
			"package_name": "rh-python38-python",
			"product_name": "Red Hat Software Collections"
		}
	],
	"public_date": "2023-08-22T00:00:00Z",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2022-48566\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-48566"
	],
	"statement": "This flaw is classified as Moderate as in contrast to an Important rating, the exploitation of this vulnerability is difficult to achieve and the outcome of the impact is breach of confidentiality.\nVersions of `python36:3.6/python36` as shipped with Red Hat Enterprise Linux 8 are marked as 'Not affected' as they just provide \"symlinks\" to the main `python3` component, which provides the interpreter of the Python programming language.\nVersions of  `python39:3.9/python39` and `python2` in various modules as shipped with Red Hat Enterprise Linux 8, `python3.11/python3.9` as shipped with Red Hat Enterprise Linux 9 and `python 3.8.14` as shipped with Red Hat Software Collections are marked as 'Not affected' as they are higher than the vulnerable version, thereby containing the fixed code.",
	"threat_severity": "Moderate"
}
