{
	"bugzilla": {
		"description": "Out of bounds read causes DoS",
		"id": "2119150",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2119150"
	},
	"csaw": false,
	"cvss3": {
		"cvss3_base_score": "7.1",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:H",
		"status": "draft"
	},
	"cwe": "CWE-125",
	"details": [
		"GNU SASL libgsasl server-side read-out-of-bounds with malicious authenticated GSS-API client"
	],
	"name": "CVE-2022-2469",
	"public_date": "2022-07-18T00:00:00Z",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2022-2469\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-2469\nhttps://lists.gnu.org/archive/html/info-gnu/2022-07/msg00003.html\nhttps://www.debian.org/security/2022/dsa-5189"
	],
	"statement": "This flaw affects Community Projects only;  no supported Red Hat products are affected.",
	"threat_severity": "Moderate",
	"upstream_fix": "libgsasl 2.0.1"
}
