{
	"affected_release": [
		{
			"advisory": "RHSA-2023:4466",
			"cpe": "cpe:/a:redhat:satellite:6.13::el8",
			"package": "python-future-0:0.18.3-1.el8pc",
			"product_name": "Red Hat Satellite 6.13 for RHEL 8",
			"release_date": "2023-08-03T00:00:00Z"
		},
		{
			"advisory": "RHSA-2023:4466",
			"cpe": "cpe:/a:redhat:satellite_capsule:6.13::el8",
			"package": "python-future-0:0.18.3-1.el8pc",
			"product_name": "Red Hat Satellite 6.13 for RHEL 8",
			"release_date": "2023-08-03T00:00:00Z"
		},
		{
			"advisory": "RHSA-2023:6818",
			"cpe": "cpe:/a:redhat:satellite:6.14::el8",
			"package": "python-future-0:0.18.3-1.el8pc",
			"product_name": "Red Hat Satellite 6.14 for RHEL 8",
			"release_date": "2023-11-08T00:00:00Z"
		},
		{
			"advisory": "RHSA-2023:6818",
			"cpe": "cpe:/a:redhat:satellite_capsule:6.14::el8",
			"package": "python-future-0:0.18.3-1.el8pc",
			"product_name": "Red Hat Satellite 6.14 for RHEL 8",
			"release_date": "2023-11-08T00:00:00Z"
		},
		{
			"advisory": "RHSA-2023:2101",
			"cpe": "cpe:/a:redhat:rhui:4::el8",
			"package": "python-future-0:0.18.3-1.0.1.el8ui",
			"product_name": "RHUI 4 for RHEL 8",
			"release_date": "2023-05-03T00:00:00Z"
		}
	],
	"bugzilla": {
		"description": "remote attackers can cause denial of service via crafted Set-Cookie header from malicious web server",
		"id": "2165866",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2165866"
	},
	"csaw": false,
	"cvss3": {
		"cvss3_base_score": "7.5",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
		"status": "verified"
	},
	"cwe": "CWE-400",
	"details": [
		"An issue discovered in Python Charmers Future 0.18.2 and earlier allows remote attackers to cause a denial of service via crafted Set-Cookie header from malicious web server.",
		"A denial of service flaw was found in Python Charmers Future. This flaw allows an attacker to send a specially crafted Set-Cookie header in an HTTP request, resulting in a loss of system availability."
	],
	"name": "CVE-2022-40899",
	"package_state": [
		{
			"cpe": "cpe:/a:redhat:cloudforms_managementengine:5",
			"fix_state": "Out of support scope",
			"package_name": "python-future",
			"product_name": "CloudForms Management Engine 5"
		},
		{
			"cpe": "cpe:/a:redhat:ansible_automation_platform:2",
			"fix_state": "Not affected",
			"package_name": "python-future",
			"product_name": "Red Hat Ansible Automation Platform 2"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Will not fix",
			"package_name": "python-futures",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/a:redhat:openshift:3.11",
			"fix_state": "Out of support scope",
			"package_name": "python-futures",
			"product_name": "Red Hat OpenShift Container Platform 3.11"
		},
		{
			"cpe": "cpe:/a:redhat:openshift:4",
			"fix_state": "Affected",
			"package_name": "future",
			"product_name": "Red Hat OpenShift Container Platform 4"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:13",
			"fix_state": "Out of support scope",
			"package_name": "future",
			"product_name": "Red Hat OpenStack Platform 13 (Queens)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:13",
			"fix_state": "Out of support scope",
			"package_name": "python-futures",
			"product_name": "Red Hat OpenStack Platform 13 (Queens)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:16.1",
			"fix_state": "Will not fix",
			"package_name": "future",
			"product_name": "Red Hat OpenStack Platform 16.1"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:16.2",
			"fix_state": "Not affected",
			"package_name": "future",
			"product_name": "Red Hat OpenStack Platform 16.2"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:17.0",
			"fix_state": "Not affected",
			"package_name": "future",
			"product_name": "Red Hat OpenStack Platform 17.0"
		},
		{
			"cpe": "cpe:/a:redhat:satellite:6",
			"fix_state": "Affected",
			"package_name": "future",
			"product_name": "Red Hat Satellite 6"
		},
		{
			"cpe": "cpe:/a:redhat:satellite:6",
			"fix_state": "Affected",
			"package_name": "tfm-pulpcore-python-future",
			"product_name": "Red Hat Satellite 6"
		}
	],
	"public_date": "2022-12-21T00:00:00Z",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2022-40899\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-40899"
	],
	"threat_severity": "Moderate"
}
