{
	"name": "CVE-2021-31542",
	"threat_severity": "Moderate",
	"public_date": "2021-05-04T00:00:00Z",
	"bugzilla": {
		"description": "django: Potential directory-traversal via uploaded files",
		"id": "1954294",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1954294"
	},
	"cvss3": {
		"cvss3_base_score": "7.5",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
		"status": "verified"
	},
	"cwe": "CWE-22",
	"details": [
		"In Django 2.2 before 2.2.21, 3.1 before 3.1.9, and 3.2 before 3.2.1, MultiPartParser, UploadedFile, and FieldFile allowed directory traversal via uploaded files with suitably crafted file names.",
		"A flaw was found in Django. `MultiPartParser`, `UploadedFile`, and `FieldFile` allowed directory-traversal via uploaded files with suitably crafted file names. The highest threat from this vulnerability is to data confidentiality."
	],
	"statement": "Red Hat Update Infrastructure is in the maintenance phase and we will not be fixing Medium/Low impact security bugs. Reference: https://access.redhat.com/support/policy/updates/rhui",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2021-31542\nhttps://nvd.nist.gov/vuln/detail/CVE-2021-31542\nhttps://www.djangoproject.com/weblog/2021/may/04/security-releases/"
	],
	"mitigation": {
		"lang": "en:us",
		"value": "Mitigation for this issue is either not available or the currently available options do not meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability."
	},
	"affected_release": [
		{
			"advisory": "RHSA-2021:5070",
			"cpe": "cpe:/a:redhat:openstack:16.1::el8",
			"package": "python-django20-0:2.0.13-16.el8ost.1",
			"product_name": "Red Hat OpenStack Platform 16.1",
			"release_date": "2021-12-09T00:00:00Z"
		},
		{
			"advisory": "RHSA-2021:4702",
			"cpe": "cpe:/a:redhat:satellite:6.10::el7",
			"package": "python3-django-0:2.2.24-1.el7pc",
			"product_name": "Red Hat Satellite 6.10 for RHEL 7",
			"release_date": "2021-11-16T00:00:00Z"
		},
		{
			"advisory": "RHSA-2021:4702",
			"cpe": "cpe:/a:redhat:satellite_capsule:6.10::el7",
			"package": "python3-django-0:2.2.24-1.el7pc",
			"product_name": "Red Hat Satellite 6.10 for RHEL 7",
			"release_date": "2021-11-16T00:00:00Z"
		}
	],
	"package_state": [
		{
			"cpe": "cpe:/a:redhat:ansible_automation_platform",
			"fix_state": "Affected",
			"package_name": "django",
			"product_name": "Red Hat Ansible Automation Platform 1.2"
		},
		{
			"cpe": "cpe:/a:redhat:ansible_automation_platform",
			"fix_state": "Affected",
			"package_name": "python-django",
			"product_name": "Red Hat Ansible Automation Platform 1.2"
		},
		{
			"cpe": "cpe:/a:redhat:ansible_tower:3",
			"fix_state": "Not affected",
			"package_name": "django",
			"product_name": "Red Hat Ansible Tower 3"
		},
		{
			"cpe": "cpe:/a:redhat:ceph_storage:2",
			"fix_state": "Out of support scope",
			"package_name": "calamari-server",
			"product_name": "Red Hat Ceph Storage 2"
		},
		{
			"cpe": "cpe:/a:redhat:ceph_storage:2",
			"fix_state": "Out of support scope",
			"package_name": "python-django",
			"product_name": "Red Hat Ceph Storage 2"
		},
		{
			"cpe": "cpe:/a:redhat:ceph_storage:3",
			"fix_state": "Out of support scope",
			"package_name": "python-django",
			"product_name": "Red Hat Ceph Storage 3"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:10",
			"fix_state": "Out of support scope",
			"package_name": "python-django",
			"product_name": "Red Hat OpenStack Platform 10 (Newton)"
		},
		{
			"cpe": "cpe:/a:redhat:openstack:13",
			"fix_state": "Will not fix",
			"package_name": "python-django",
			"product_name": "Red Hat OpenStack Platform 13 (Queens)"
		},
		{
			"cpe": "cpe:/a:redhat:satellite:6",
			"fix_state": "Will not fix",
			"package_name": "python-django",
			"product_name": "Red Hat Satellite 6"
		},
		{
			"cpe": "cpe:/a:redhat:storage:3",
			"fix_state": "Will not fix",
			"package_name": "python-django",
			"product_name": "Red Hat Storage 3"
		},
		{
			"cpe": "cpe:/a:redhat:rhui:3",
			"fix_state": "Will not fix",
			"package_name": "python-django",
			"product_name": "Red Hat Update Infrastructure 3 for Cloud Providers"
		}
	],
	"upstream_fix": "Django 3.2.1, Django 3.1.9, Django 2.2.21",
	"csaw": false
}
