{
	"acknowledgement": "This issue was discovered by Miklos Szeredi (Red Hat).",
	"affected_release": [
		{
			"advisory": "RHSA-2021:5241",
			"cpe": "cpe:/a:redhat:enterprise_linux:8::nfv",
			"package": "kernel-rt-0:4.18.0-348.7.1.rt7.137.el8_5",
			"product_name": "Red Hat Enterprise Linux 8",
			"release_date": "2021-12-21T00:00:00Z"
		},
		{
			"advisory": "RHSA-2021:5227",
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"package": "kernel-0:4.18.0-348.7.1.el8_5",
			"product_name": "Red Hat Enterprise Linux 8",
			"release_date": "2021-12-21T00:00:00Z"
		}
	],
	"bugzilla": {
		"description": "In Overlayfs missing a check for a negative dentry before calling vfs_rename()",
		"id": "2013242",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2013242"
	},
	"csaw": false,
	"cvss3": {
		"cvss3_base_score": "5.5",
		"cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
		"status": "verified"
	},
	"cwe": "CWE-362",
	"details": [
		"A race condition accessing file object in the Linux kernel OverlayFS subsystem was found in the way users do rename in specific way with OverlayFS. A local user could use this flaw to crash the system.",
		"A race condition accessing file object in the Linux kernel OverlayFS subsystem was found in the way users do rename in specific way with OverlayFS. A local user could use this flaw to crash the system."
	],
	"mitigation": {
		"lang": "en:us",
		"value": "Mitigation for this issue is either not available or the currently available options don't meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability."
	},
	"name": "CVE-2021-20321",
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:5",
			"fix_state": "Not affected",
			"package_name": "kernel",
			"product_name": "Red Hat Enterprise Linux 5"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:6",
			"fix_state": "Not affected",
			"package_name": "kernel",
			"product_name": "Red Hat Enterprise Linux 6"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Out of support scope",
			"package_name": "kernel",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Out of support scope",
			"package_name": "kernel-rt",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:9",
			"fix_state": "Not affected",
			"package_name": "kernel",
			"product_name": "Red Hat Enterprise Linux 9"
		}
	],
	"public_date": "2021-10-11T09:00:00Z",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2021-20321\nhttps://nvd.nist.gov/vuln/detail/CVE-2021-20321\nhttps://lore.kernel.org/all/20211011134508.748956131@linuxfoundation.org/"
	],
	"threat_severity": "Moderate",
	"upstream_fix": "kernel 5.15-rc5"
}
