{
	"bugzilla": {
		"description": "CVE-2021-43400 bluez: use-after-free in gatt-database.c",
		"id": "2020523",
		"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2020523"
	},
	"csaw": false,
	"cvss3": {
		"cvss3_base_score": "9.1",
		"cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
		"status": "draft"
	},
	"cwe": "CWE-416",
	"details": [
		"An issue was discovered in gatt-database.c in BlueZ 5.61. A use-after-free can occur when a client disconnects during D-Bus processing of a WriteValue call."
	],
	"name": "CVE-2021-43400",
	"package_state": [
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:6",
			"fix_state": "Not affected",
			"package_name": "bluez",
			"product_name": "Red Hat Enterprise Linux 6"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:7",
			"fix_state": "Not affected",
			"package_name": "bluez",
			"product_name": "Red Hat Enterprise Linux 7"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:8",
			"fix_state": "Not affected",
			"package_name": "bluez",
			"product_name": "Red Hat Enterprise Linux 8"
		},
		{
			"cpe": "cpe:/o:redhat:enterprise_linux:9",
			"fix_state": "Not affected",
			"package_name": "bluez",
			"product_name": "Red Hat Enterprise Linux 9"
		}
	],
	"public_date": "2021-11-05T00:00:00Z",
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2021-43400\nhttps://nvd.nist.gov/vuln/detail/CVE-2021-43400"
	],
	"threat_severity": "Moderate",
	"upstream_fix": "bluez 5.62"
}
